# Generated by Django 4.2.2 on 2023-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='emails_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
