# Generated by Django 4.2.2 on 2023-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0003_remove_file_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(default='A generic file'),
        ),
    ]
